Feature/#37 bonus part cone sanghwal
devJgo/miniRT pull request #49
Opened 2023-06-23 08:48 UTC by idealflower-k

## Overview

cone rendering구현을 완료했습니다!

## PR Checklist

- [ ] I read and included theses actions below

1. I have read the [Contributing Guide](https://github.com/jgodv/miniRT/.github/CONTRIBUTING.md)
2. I have written documents and tests, if needed.

2023-06-23 12:24 UTC, devJgo commented
<img width="1192" alt="image" src="https://github.com/devJgo/miniRT/assets/89189246/960fd231-0f69-4cb4-b617-6129aef27934">
오른쪽 콘이 빛이 적용이 안되는 것 같아요! 무슨 문제가 있을까요?

2023-06-23 13:11 UTC, idealflower-k commented
음... cone 좌표랑 벡터 정보가 어떻게 되나요?

2023-06-23 13:28 UTC, devJgo commented
A 0.7 255,255,255


C 0,0,10 0,0,-1 90

L 0,0,20 0.7 255,255,255


co 0,0,0 1,1,-0.3 2 2 123,42,230
co 5,0,0 1,2,-0.3 2 2 12,222,230

이렇게 테스트했습니다.

2023-06-23 13:39 UTC, idealflower-k commented
테스트를 해보니 12,222,230 해당 rgb값의 이슈인거 같습니다. rgb값을 변경하고 한번 확인 부탁드립니다

2023-06-25 01:38 UTC, devJgo commented on src/bonus/design_patterns/all
해당 파일 삭제 해주세요!

2023-06-25 01:40 UTC, devJgo commented on src/bonus/scene/all
삭제 부탁드립니다~

2023-06-25 01:40 UTC, devJgo commented on src/bonus/utils/all
삭제 하고 다시 pr부탁드립니다~

2023-06-25 01:41 UTC, devJgo requested changes
all 파일만 삭제하고 다시 pr 해주세요! cone렌더는 여러가지 케이스를 넣어봤는데 잘 되네요!! 
그런데 너무 밝을 때는 빛이 적용이 안되는 것처럼 보여서 아쉽긴하군요.

2023-06-25 13:44 UTC, devJgo approved these changes
좋습니다!! 고생하셨습니다!

2023-06-26 10:52 UTC, merged